### PR TITLE
Convert cat() to message() 

### PR DESCRIPTION
**Pull request by jmclawson**
Currently, Stylo doesn't work well with R Markdown, as the output on the console is too verbose, with no option for a quiet run. R Markdown documents allow for juxtaposition of code, results, and analysis; in such an environment, console comments are undesirable.

One option would be to add a "quiet" parameter, but that would require adding a logical test before each `cat()` call.

Easier is to rely on R's native message handling. Converting `cat()` to `message()` makes this possible and allows Stylo to work well with R Markdown and with Knitr's `message=FALSE` chunk option. (See [http://yihui.name/knitr/options/](http://yihui.name/knitr/options/).)

### CODE REVIEW

**Comment by computationalstylistics** [comment]
Thanks a lot for this contribution! I've been thinking of replacing all the instances of cat() with something else, e.g. message(), but the TODO list is always overwhelmed by some urgent fixes! Frankly, being a big fan of Rmarkdown, I haven't been using it with Stylo so far. Great to know that it can be forced to work OK.

**Comment by jmclawson** [comment]
I'm sorry. I may have accidentally also submitted a second proposed change in "txt.to.words.ext.R", but that doesn't belong with this issue. (And here I thought I'd figured out how to work GitHub...)

I've backed that change out from my branch in hopes that it didn't interfere with anything!

**Comment by computationalstylistics** [comment]
No problem! That's another change I was sort of thinking of, as well as replacing "j" with "i" for Latin

**Comment by jmclawson** [comment]
Another good idea! Thanks for the great package and active development.

**Pull request merged**
